"use client";

import { CheckCircle2, XCircle, AlertTriangle, Leaf, Percent, FlaskConical, RotateCcw } from "lucide-react";

const statusConfig = {
  "High Quality": {
    icon: <CheckCircle2 className="h-5 w-5" />,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
    border: "border-emerald-200",
    bar: "bg-emerald-500",
    badge: "bg-emerald-100 text-emerald-700",
  },
  "Medium Quality": {
    icon: <AlertTriangle className="h-5 w-5" />,
    color: "text-amber-600",
    bg: "bg-amber-50",
    border: "border-amber-200",
    bar: "bg-amber-400",
    badge: "bg-amber-100 text-amber-700",
  },
  Rejected: {
    icon: <XCircle className="h-5 w-5" />,
    color: "text-red-600",
    bg: "bg-red-50",
    border: "border-red-200",
    bar: "bg-red-500",
    badge: "bg-red-100 text-red-700",
  },
};

export default function ResultDisplay({ result, originalImage, onReset }) {
  const config = statusConfig[result.qualityStatus];

  return (
    <div className="flex flex-col gap-6">
      <div className={`flex items-center gap-3 rounded-xl border p-4 ${config.bg} ${config.border}`}>
        <span className={config.color}>{config.icon}</span>
        <div>
          <p className={`font-bold text-lg ${config.color}`}>{result.qualityStatus}</p>
          <p className="text-sm text-zinc-600">
            {result.qualityStatus === "High Quality"
              ? "This leaf meets the medical grade threshold and is suitable for production."
              : result.qualityStatus === "Medium Quality"
              ? "Partially affected. Use with caution or blend with healthier stock."
              : "Disease spread exceeds acceptable limits. Reject from medicinal production."}
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div className="flex flex-col gap-2">
          <p className="text-xs font-semibold uppercase tracking-wider text-zinc-500">Original Image</p>
          <div className="overflow-hidden rounded-xl border border-zinc-200">
            <img src={originalImage} alt="Original leaf" className="w-full object-cover aspect-square" />
          </div>
        </div>
        <div className="flex flex-col gap-2">
          <p className="text-xs font-semibold uppercase tracking-wider text-zinc-500">Disease Mask</p>
          <div className="relative overflow-hidden rounded-xl border border-zinc-200 aspect-square bg-zinc-100 flex items-center justify-center">
            {result.maskImageUrl ? (
              <img src={result.maskImageUrl} alt="Disease mask" className="w-full h-full object-cover" />
            ) : (
              <div className="text-center px-4">
                <FlaskConical className="mx-auto h-8 w-8 text-zinc-400 mb-2" />
                <p className="text-xs text-zinc-400">Mask generated by U-Net model</p>
              </div>
            )}
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <div className="flex flex-col gap-2 rounded-xl border border-zinc-200 bg-white p-4">
          <div className="flex items-center gap-2 text-zinc-500">
            <Leaf className="h-4 w-4" />
            <span className="text-xs font-semibold uppercase tracking-wider">Disease</span>
          </div>
          <p className="text-xl font-bold capitalize text-zinc-900">{result.diseaseName}</p>
        </div>

        <div className="flex flex-col gap-2 rounded-xl border border-zinc-200 bg-white p-4">
          <div className="flex items-center gap-2 text-zinc-500">
            <Percent className="h-4 w-4" />
            <span className="text-xs font-semibold uppercase tracking-wider">Disease Spread</span>
          </div>
          <p className="text-xl font-bold text-zinc-900">{result.diseaseSpreadPercent.toFixed(1)}%</p>
          <div className="h-1.5 w-full overflow-hidden rounded-full bg-zinc-100">
            <div className={`h-full rounded-full transition-all duration-700 ${config.bar}`} style={{ width: `${result.diseaseSpreadPercent}%` }} />
          </div>
        </div>

        <div className="flex flex-col gap-2 rounded-xl border border-zinc-200 bg-white p-4">
          <div className="flex items-center gap-2 text-zinc-500">
            <CheckCircle2 className="h-4 w-4" />
            <span className="text-xs font-semibold uppercase tracking-wider">Healthy Tissue</span>
          </div>
          <p className="text-xl font-bold text-zinc-900">{result.healthyTissuePercent.toFixed(1)}%</p>
          <div className="h-1.5 w-full overflow-hidden rounded-full bg-zinc-100">
            <div className="h-full rounded-full bg-emerald-500 transition-all duration-700" style={{ width: `${result.healthyTissuePercent}%` }} />
          </div>
        </div>
      </div>

      <div className={`inline-flex items-center gap-2 self-start rounded-full px-4 py-2 text-sm font-semibold ${config.badge}`}>
        {config.icon}
        Medicinal Quality Grade: {result.qualityStatus}
      </div>

      <button
        onClick={onReset}
        className="flex items-center gap-2 self-start rounded-full border border-zinc-300 bg-white px-5 py-2.5 text-sm font-semibold text-zinc-700 transition-all hover:bg-zinc-50"
      >
        <RotateCcw className="h-4 w-4" />
        Analyze Another Leaf
      </button>
    </div>
  );
}
